// Mock data for the Reservist App commander dashboard.
// Unit: Mahlaka 6 — Carmel (a platoon, ~24 reservists).

window.UNIT = {
  name: "Mahlaka 6 — Carmel",
  shortName: "Mahlaka 6",
  crest: "M6",
  commanders: ["Yoni Avraham", "Daniel Katz"],
  memberCount: 24,
  established: "Established 2021",
  invite: "carmel-6-J3xK",
};

// Roles available in this unit (commander-defined per PRD §7.2)
window.ROLES = [
  "Squad Leader",
  "Rifleman",
  "Combat Medic",
  "Combat Engineer",
  "Sharpshooter",
  "MAG Gunner",
  "RPG Gunner",
  "Driver",
  "Signals",
  "Drone Operator",
  "Intel Analyst",
  "Logistics",
];

// Skills tag set (commander-defined per PRD §7.2)
window.SKILLS = [
  "First Aid Cert.",
  "Combat Medic Cert.",
  "HMMWV",
  "Heavy Truck",
  "Night Ops",
  "Urban Combat",
  "Arabic",
  "English (Fluent)",
  "Russian",
  "Drone Op.",
  "Sniper Cert.",
  "Mechanic",
  "Comms Tech",
  "Krav Maga Inst.",
  "Cyber",
  "GIS / Maps",
];

const tone = (i) => i % 8;

window.MEMBERS = [
  {
    id: "u01", name: "Yoni Avraham", initials: "YA", tone: tone(0),
    role: "Squad Leader", isCommander: true,
    phone: "+972 54-221-8843", status: "available",
    statusNote: "Returning from south, ETA 18:00",
    statusUntil: null,
    skills: ["Urban Combat", "Night Ops", "Arabic"],
    joined: "2021-03",
    lastSeen: "active now",
    callsThisYear: 4,
  },
  {
    id: "u02", name: "Tamar Levi", initials: "TL", tone: tone(1),
    role: "Combat Medic",
    phone: "+972 50-887-4421", status: "standby",
    statusNote: "On 12h standby through Friday",
    statusUntil: "2026-05-22",
    skills: ["Combat Medic Cert.", "First Aid Cert.", "English (Fluent)"],
    joined: "2021-08",
    lastSeen: "2h ago",
    callsThisYear: 6,
  },
  {
    id: "u03", name: "Eitan Cohen", initials: "EC", tone: tone(2),
    role: "Driver",
    phone: "+972 52-654-1109", status: "available",
    statusNote: null, statusUntil: null,
    skills: ["HMMWV", "Heavy Truck", "Mechanic", "Night Ops"],
    joined: "2021-03",
    lastSeen: "1d ago",
    callsThisYear: 5,
  },
  {
    id: "u04", name: "Noa Shapira", initials: "NS", tone: tone(3),
    role: "Signals",
    phone: "+972 54-339-7720", status: "released",
    statusNote: "Released this morning, back home",
    statusUntil: null,
    skills: ["Comms Tech", "Cyber", "English (Fluent)"],
    joined: "2022-01",
    lastSeen: "6h ago",
    callsThisYear: 7,
  },
  {
    id: "u05", name: "Avi Mizrahi", initials: "AM", tone: tone(4),
    role: "Sharpshooter",
    phone: "+972 53-115-4408", status: "available",
    statusNote: null, statusUntil: null,
    skills: ["Sniper Cert.", "Night Ops", "Urban Combat"],
    joined: "2021-05",
    lastSeen: "active now",
    callsThisYear: 3,
  },
  {
    id: "u06", name: "Maya Ben-David", initials: "MB", tone: tone(5),
    role: "Intel Analyst",
    phone: "+972 54-008-2287", status: "unavailable",
    statusNote: "Abroad — research conference",
    statusUntil: "2026-08-12",
    skills: ["GIS / Maps", "English (Fluent)", "Arabic", "Cyber"],
    joined: "2022-04",
    lastSeen: "3d ago",
    callsThisYear: 2,
  },
  {
    id: "u07", name: "Itai Rosen", initials: "IR", tone: tone(6),
    role: "Combat Engineer",
    phone: "+972 52-771-3309", status: "available",
    statusNote: null, statusUntil: null,
    skills: ["Urban Combat", "Mechanic", "Night Ops"],
    joined: "2021-07",
    lastSeen: "4h ago",
    callsThisYear: 4,
  },
  {
    id: "u08", name: "Shira Peretz", initials: "SP", tone: tone(7),
    role: "Combat Medic",
    phone: "+972 50-462-7785", status: "standby",
    statusNote: "Pinning for night call-up",
    statusUntil: "2026-05-18",
    skills: ["Combat Medic Cert.", "First Aid Cert.", "Night Ops"],
    joined: "2021-09",
    lastSeen: "active now",
    callsThisYear: 5,
  },
  {
    id: "u09", name: "Daniel Katz", initials: "DK", tone: tone(0),
    role: "Squad Leader", isCommander: true,
    phone: "+972 54-902-1126", status: "available",
    statusNote: null, statusUntil: null,
    skills: ["Urban Combat", "Krav Maga Inst.", "Arabic"],
    joined: "2021-03",
    lastSeen: "active now",
    callsThisYear: 6,
  },
  {
    id: "u10", name: "Lior Friedman", initials: "LF", tone: tone(1),
    role: "RPG Gunner",
    phone: "+972 53-200-8841", status: "available",
    statusNote: null, statusUntil: null,
    skills: ["Night Ops", "Urban Combat"],
    joined: "2022-02",
    lastSeen: "1d ago",
    callsThisYear: 4,
  },
  {
    id: "u11", name: "Roni Bar-On", initials: "RB", tone: tone(2),
    role: "MAG Gunner",
    phone: "+972 54-115-6601", status: "released",
    statusNote: "Released yesterday",
    statusUntil: null,
    skills: ["Heavy Truck", "Urban Combat"],
    joined: "2021-04",
    lastSeen: "12h ago",
    callsThisYear: 7,
  },
  {
    id: "u12", name: "Uri Goldstein", initials: "UG", tone: tone(3),
    role: "Rifleman",
    phone: "+972 52-441-9908", status: "available",
    statusNote: null, statusUntil: null,
    skills: ["Urban Combat", "Russian"],
    joined: "2022-06",
    lastSeen: "active now",
    callsThisYear: 3,
  },
  {
    id: "u13", name: "Tal Shemesh", initials: "TS", tone: tone(4),
    role: "Drone Operator",
    phone: "+972 50-789-2244", status: "standby",
    statusNote: "On-call from base",
    statusUntil: "2026-05-20",
    skills: ["Drone Op.", "Comms Tech", "English (Fluent)"],
    joined: "2021-11",
    lastSeen: "1h ago",
    callsThisYear: 5,
  },
  {
    id: "u14", name: "Omer Halevi", initials: "OH", tone: tone(5),
    role: "Driver",
    phone: "+972 54-660-3317", status: "available",
    statusNote: null, statusUntil: null,
    skills: ["Heavy Truck", "Mechanic"],
    joined: "2021-06",
    lastSeen: "active now",
    callsThisYear: 4,
  },
  {
    id: "u15", name: "Gal Adler", initials: "GA", tone: tone(6),
    role: "Signals",
    phone: "+972 52-009-4488", status: "unavailable",
    statusNote: "Exam period (final year, Hebrew U)",
    statusUntil: "2026-06-28",
    skills: ["Comms Tech", "English (Fluent)"],
    joined: "2022-09",
    lastSeen: "5d ago",
    callsThisYear: 2,
  },
  {
    id: "u16", name: "Yair Ben-Ami", initials: "YB", tone: tone(7),
    role: "Rifleman",
    phone: "+972 53-118-7706", status: "available",
    statusNote: null, statusUntil: null,
    skills: ["Urban Combat", "Night Ops"],
    joined: "2022-04",
    lastSeen: "8h ago",
    callsThisYear: 3,
  },
  {
    id: "u17", name: "Hadar Stern", initials: "HS", tone: tone(0),
    role: "Combat Medic",
    phone: "+972 50-228-5520", status: "released",
    statusNote: "Released — three days off",
    statusUntil: null,
    skills: ["Combat Medic Cert.", "First Aid Cert.", "Krav Maga Inst."],
    joined: "2021-10",
    lastSeen: "yesterday",
    callsThisYear: 6,
  },
  {
    id: "u18", name: "Amit Sapir", initials: "AS", tone: tone(1),
    role: "Sharpshooter",
    phone: "+972 54-771-6644", status: "standby",
    statusNote: "Ready, awaiting brief",
    statusUntil: "2026-05-21",
    skills: ["Sniper Cert.", "Night Ops"],
    joined: "2022-03",
    lastSeen: "30m ago",
    callsThisYear: 4,
  },
  {
    id: "u19", name: "Nadav Reichman", initials: "NR", tone: tone(2),
    role: "Combat Engineer",
    phone: "+972 53-665-8821", status: "available",
    statusNote: null, statusUntil: null,
    skills: ["Mechanic", "Urban Combat", "Night Ops"],
    joined: "2021-08",
    lastSeen: "active now",
    callsThisYear: 5,
  },
  {
    id: "u20", name: "Idan Carmel", initials: "IC", tone: tone(3),
    role: "Rifleman",
    phone: "+972 54-449-1129", status: "available",
    statusNote: null, statusUntil: null,
    skills: ["Urban Combat", "Russian"],
    joined: "2022-07",
    lastSeen: "4h ago",
    callsThisYear: 3,
  },
  {
    id: "u21", name: "Liat Geller", initials: "LG", tone: tone(4),
    role: "Intel Analyst",
    phone: "+972 50-880-3309", status: "available",
    statusNote: null, statusUntil: null,
    skills: ["GIS / Maps", "Arabic", "English (Fluent)", "Cyber"],
    joined: "2021-12",
    lastSeen: "active now",
    callsThisYear: 4,
  },
  {
    id: "u22", name: "Ben Naveh", initials: "BN", tone: tone(5),
    role: "Logistics",
    phone: "+972 52-339-7740", status: "available",
    statusNote: null, statusUntil: null,
    skills: ["Heavy Truck", "Mechanic"],
    joined: "2022-05",
    lastSeen: "2h ago",
    callsThisYear: 3,
  },
  {
    id: "u23", name: "Rotem Avidan", initials: "RA", tone: tone(6),
    role: "Combat Engineer",
    phone: "+972 54-200-1185", status: "unavailable",
    statusNote: "Wedding, away",
    statusUntil: "2026-05-19",
    skills: ["Urban Combat", "Mechanic"],
    joined: "2021-07",
    lastSeen: "1d ago",
    callsThisYear: 5,
  },
  {
    id: "u24", name: "Shai Klein", initials: "SK", tone: tone(7),
    role: "Rifleman",
    phone: "+972 53-880-2204", status: "available",
    statusNote: null, statusUntil: null,
    skills: ["Urban Combat", "Krav Maga Inst."],
    joined: "2022-10",
    lastSeen: "active now",
    callsThisYear: 2,
  },
];

window.STATUS_LABEL = {
  available: "Available",
  standby: "Standby",
  released: "Released",
  unavailable: "Unavailable",
};

// Sample activity feed (PRD §7.3)
window.ACTIVITY = [
  { id: "a1", tone: "urgent", who: "You", verb: "posted an urgent call-up", what: "Northern QRF, 6 needed", when: "12 min ago" },
  { id: "a2", tone: "accent", who: "Tamar Levi", verb: "set status to", what: "Standby (through Fri)", when: "32 min ago" },
  { id: "a3", tone: null, who: "Eitan Cohen", verb: "updated phone number", what: null, when: "1h ago" },
  { id: "a4", tone: "accent", who: "Daniel Katz", verb: "assigned", what: "Avi Mizrahi to Outpost Rotation", when: "2h ago" },
  { id: "a5", tone: null, who: "Noa Shapira", verb: "set status to", what: "Released", when: "4h ago" },
  { id: "a6", tone: null, who: "Maya Ben-David", verb: "set status to", what: "Unavailable (abroad)", when: "yesterday" },
  { id: "a7", tone: "accent", who: "Hadar Stern", verb: "joined the unit", what: null, when: "3 days ago" },
];

// Upcoming slots (PRD §7.5)
window.SLOTS = [
  {
    id: "s1", title: "Northern QRF — Sector 4", urgent: true,
    date: "Today, 22:00",  duration: "12h",
    location: "Tzomet Bilu staging",
    needed: 6, filled: 2,
    role: "Rifleman", skills: ["Night Ops"],
    assignees: ["u01", "u05"],
  },
  {
    id: "s2", title: "Outpost Rotation — Givat HaShlosha",
    date: "Mon May 19, 06:00", duration: "72h",
    location: "Givat HaShlosha",
    needed: 4, filled: 4,
    role: "Rifleman", skills: [],
    assignees: ["u05", "u12", "u16", "u20"],
  },
  {
    id: "s3", title: "Convoy escort — Route 90",
    date: "Wed May 21, 04:30", duration: "10h",
    location: "Beit She'an staging",
    needed: 3, filled: 1,
    role: "Driver", skills: ["Heavy Truck"],
    assignees: ["u14"],
  },
];
